export const GRAPH_URL_MESSAGES = "https://graph.facebook.com/v2.6/me/messages"
export const VERIFY_TOKEN = "TriPrsaNaHrudi89"
export const PAGE_ACCESS_TOKEN = "EAAfRmLwEsvsBALByU5ZCGxq5OrfUZCrlnA6SEMozM36l6gItjfyfZAWZBfGrYgM0SLyg7PPo3ZANKb6SV1ZB8NRNOZAkd6kYcFkKDvZAn7Q5ht9EjnJeeA4sfBbzo6vNKmEICfBuZBjbIdguEJXOYRZBvSGqM4ZARGKHSLiJRZA2jETtPm8EuHf6cZBsu"
